[2023-04-06T13:32:06.058+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-27T00:00:00+00:00 [queued]>
[2023-04-06T13:32:06.101+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-27T00:00:00+00:00 [queued]>
[2023-04-06T13:32:06.103+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:32:06.103+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-06T13:32:06.105+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:32:06.323+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_name> on 2022-05-27 00:00:00+00:00
[2023-04-06T13:32:06.333+0000] {standard_task_runner.py:55} INFO - Started process 4682 to run task
[2023-04-06T13:32:06.344+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v06', 'get_name', 'scheduled__2022-05-27T00:00:00+00:00', '--job-id', '4644', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp8783kiue']
[2023-04-06T13:32:06.348+0000] {standard_task_runner.py:83} INFO - Job 4644: Subtask get_name
[2023-04-06T13:32:06.546+0000] {local_task_job.py:113} ERROR - Received SIGTERM. Terminating subprocesses
[2023-04-06T13:32:06.548+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4682. PIDs of all processes in the group: [4682]
[2023-04-06T13:32:06.548+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4682
[2023-04-06T13:32:06.582+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4682, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='13:32:05') (4682) terminated with exit code Negsignal.SIGTERM
[2023-04-06T13:32:06.582+0000] {local_task_job.py:212} INFO - Task exited with return code 143
[2023-04-06T13:32:06.820+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
