[2023-04-05T12:30:58.671+0000] {processor.py:153} INFO - Started process (PID=379) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:30:58.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:30:58.672+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:58.672+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:30:58.714+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:30:59.003+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.003+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:our_first_dag
[2023-04-05T12:30:59.013+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.013+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:our_first_dag
[2023-04-05T12:30:59.021+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.021+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:our_first_dag
[2023-04-05T12:30:59.022+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.022+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:30:59.045+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.045+0000] {dag.py:2726} INFO - Creating ORM DAG for our_first_dag
[2023-04-05T12:30:59.065+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.065+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:30:59.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.417 seconds
[2023-04-05T12:30:59.682+0000] {processor.py:153} INFO - Started process (PID=384) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:30:59.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:30:59.683+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.683+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:30:59.686+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:30:59.685+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 5, in <module>
    defa
NameError: name 'defa' is not defined
[2023-04-05T12:30:59.686+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:30:59.704+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:31:02.706+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:02.707+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:02.708+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:02.708+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:02.709+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:02.709+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8
    with DAG(
       ^
SyntaxError: invalid syntax
[2023-04-05T12:31:02.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:02.728+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:31:05.756+0000] {processor.py:153} INFO - Started process (PID=394) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:05.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:05.758+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:05.757+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:05.774+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:05.786+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:05.786+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:05.843+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:05.842+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:05.875+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.121 seconds
[2023-04-05T12:31:06.899+0000] {processor.py:153} INFO - Started process (PID=399) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:06.899+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:06.900+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:06.900+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:06.915+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:06.926+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:06.926+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:06.967+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:06.967+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:06.991+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.094 seconds
[2023-04-05T12:31:11.929+0000] {processor.py:153} INFO - Started process (PID=404) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:11.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:11.930+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:11.930+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:11.946+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:11.961+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:11.960+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:12.003+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:12.003+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:12.033+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.107 seconds
[2023-04-05T12:31:14.046+0000] {processor.py:153} INFO - Started process (PID=409) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:14.047+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:14.048+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:14.048+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:14.066+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:14.078+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:14.078+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:14.120+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:14.120+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:14.148+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.106 seconds
[2023-04-05T12:31:16.073+0000] {processor.py:153} INFO - Started process (PID=414) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:16.074+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:16.075+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:16.075+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:16.094+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:16.107+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:16.106+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:16.153+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:16.153+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:16.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.109 seconds
[2023-04-05T12:31:17.177+0000] {processor.py:153} INFO - Started process (PID=426) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:17.178+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:17.178+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:17.178+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:17.193+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:17.204+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:17.204+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:17.244+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:17.244+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:17.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.093 seconds
[2023-04-05T12:31:22.235+0000] {processor.py:153} INFO - Started process (PID=431) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:22.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:22.236+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:22.236+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:22.238+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:22.237+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2023-04-05T12:31:22.239+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:22.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T12:31:26.264+0000] {processor.py:153} INFO - Started process (PID=436) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:26.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:26.266+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:26.265+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:26.284+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:26.301+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:26.301+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:31:26.354+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:26.354+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-01-01T00:00:00+00:00, run_after=2021-01-02T00:00:00+00:00
[2023-04-05T12:31:26.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.128 seconds
[2023-04-05T12:31:32.333+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:32.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:32.335+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:32.335+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:32.338+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:32.337+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minutes=5),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:31:32.338+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:32.365+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2023-04-05T12:31:33.345+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:33.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:33.347+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:33.346+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:33.349+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:33.348+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minutes=5),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:31:33.350+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:33.374+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2023-04-05T12:31:39.422+0000] {processor.py:153} INFO - Started process (PID=451) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:39.422+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:39.423+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:39.422+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:39.425+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:39.424+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minutes=5),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:31:39.426+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:39.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:31:47.472+0000] {processor.py:153} INFO - Started process (PID=464) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:47.473+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:47.474+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:47.474+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:47.476+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:47.476+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:31:47.477+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:47.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2023-04-05T12:31:48.513+0000] {processor.py:153} INFO - Started process (PID=469) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:48.514+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:31:48.514+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:48.514+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:48.518+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:31:48.517+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:31:48.518+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:31:48.541+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2023-04-05T12:32:04.613+0000] {processor.py:153} INFO - Started process (PID=474) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:04.613+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:32:04.614+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:04.614+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:04.616+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:04.616+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:32:04.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:04.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2023-04-05T12:32:07.649+0000] {processor.py:153} INFO - Started process (PID=479) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:07.649+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:32:07.650+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:07.650+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:07.652+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:07.651+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:32:07.652+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:07.674+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2023-04-05T12:32:21.763+0000] {processor.py:153} INFO - Started process (PID=491) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:21.765+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:32:21.766+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:21.766+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:21.768+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:21.767+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:32:21.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:21.787+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2023-04-05T12:32:50.970+0000] {processor.py:153} INFO - Started process (PID=502) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:50.971+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:32:50.971+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:50.971+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:50.973+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:32:50.972+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 3
    from airflow
                ^
SyntaxError: invalid syntax
[2023-04-05T12:32:50.973+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:32:50.991+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T12:33:00.038+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:00.039+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:00.039+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:00.039+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:00.041+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:00.040+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 3
    from airflow.opera
                     ^
SyntaxError: invalid syntax
[2023-04-05T12:33:00.041+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:00.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T12:33:08.107+0000] {processor.py:153} INFO - Started process (PID=512) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:08.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:08.108+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:08.108+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:08.111+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:08.110+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 3, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2023-04-05T12:33:08.112+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:08.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:33:17.166+0000] {processor.py:153} INFO - Started process (PID=524) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:17.167+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:17.168+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:17.168+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:17.178+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:17.177+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:33:17.178+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:17.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2023-04-05T12:33:26.260+0000] {processor.py:153} INFO - Started process (PID=529) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:26.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:26.261+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:26.261+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:26.263+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:26.262+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 20
    task1=
         ^
SyntaxError: invalid syntax
[2023-04-05T12:33:26.263+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:26.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2023-04-05T12:33:28.282+0000] {processor.py:153} INFO - Started process (PID=534) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:28.282+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:28.283+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:28.283+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:28.285+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:28.284+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 20
    task1=BashOperator(
                      ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:28.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:28.305+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:33:30.317+0000] {processor.py:153} INFO - Started process (PID=539) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:30.318+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:30.318+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:30.318+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:30.320+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:30.319+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:30.320+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:30.340+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:33:32.343+0000] {processor.py:153} INFO - Started process (PID=544) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:32.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:32.344+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:32.344+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:32.346+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:32.345+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    task_id='task1',
                   ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:32.346+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:32.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:33:35.389+0000] {processor.py:153} INFO - Started process (PID=549) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:35.390+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:35.391+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:35.390+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:35.393+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:35.393+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    task_id='first_task',
                        ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:35.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:35.413+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:33:42.445+0000] {processor.py:153} INFO - Started process (PID=554) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:42.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:42.447+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:42.446+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:42.448+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:42.448+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 22
    bash_command
               ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:42.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:42.467+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:33:43.469+0000] {processor.py:153} INFO - Started process (PID=559) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:43.470+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:43.471+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:43.470+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:43.473+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:43.472+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 22
    bash_command=
                ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:43.473+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:43.490+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T12:33:44.497+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:44.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:33:44.499+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:44.498+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:44.500+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:33:44.500+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 22
    bash_command='echo "Hello World!"'
                                     ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:33:44.501+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:33:44.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:34:01.633+0000] {processor.py:153} INFO - Started process (PID=576) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:01.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:01.635+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:01.635+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:01.638+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:01.637+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 22
    bash_command=''
                  ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:34:01.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:01.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:34:03.653+0000] {processor.py:153} INFO - Started process (PID=581) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:03.654+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:03.655+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:03.654+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:03.657+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:03.656+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 22
    bash_command='echo'
                      ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:34:03.657+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:03.674+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2023-04-05T12:34:10.721+0000] {processor.py:153} INFO - Started process (PID=586) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:10.722+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:10.723+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:10.723+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:10.725+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:10.724+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 22
    bash_command='echo Hello World, this is the first task'
                                                          ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:34:10.725+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:10.745+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:34:16.762+0000] {processor.py:153} INFO - Started process (PID=591) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:16.762+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:16.763+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:16.763+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:16.765+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:16.764+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:34:16.766+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:16.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:34:24.838+0000] {processor.py:153} INFO - Started process (PID=602) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:24.839+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:24.840+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:24.839+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:24.847+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:24.846+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:34:24.847+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:24.872+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2023-04-05T12:34:26.858+0000] {processor.py:153} INFO - Started process (PID=607) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:26.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:26.860+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:26.859+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:26.865+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:26.864+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:34:26.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:26.882+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:34:27.869+0000] {processor.py:153} INFO - Started process (PID=612) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:27.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:27.870+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:27.870+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:27.876+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:27.875+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:34:27.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:27.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2023-04-05T12:34:58.055+0000] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:58.056+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:34:58.057+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:58.056+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:58.063+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:34:58.062+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:34:58.063+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:34:58.080+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:35:28.240+0000] {processor.py:153} INFO - Started process (PID=638) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:35:28.240+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:35:28.241+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:35:28.241+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:35:28.245+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:35:28.245+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minute=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:35:28.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:35:28.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:35:40.323+0000] {processor.py:153} INFO - Started process (PID=643) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:35:40.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:35:40.325+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:35:40.325+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:35:40.331+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:35:40.330+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:35:40.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:35:40.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2023-04-05T12:36:09.524+0000] {processor.py:153} INFO - Started process (PID=655) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:09.524+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:36:09.525+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:36:09.525+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:09.531+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:36:09.530+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:36:09.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:09.548+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:36:32.659+0000] {processor.py:153} INFO - Started process (PID=667) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:32.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:36:32.660+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:36:32.660+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:32.667+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:36:32.666+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:36:32.667+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:32.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:36:33.681+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:33.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:36:33.682+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:36:33.682+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:33.687+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:36:33.687+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:36:33.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:36:33.705+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:37:03.981+0000] {processor.py:153} INFO - Started process (PID=685) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:37:03.981+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:37:03.982+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:37:03.982+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:37:03.987+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:37:03.987+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:37:03.988+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:37:04.009+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2023-04-05T12:37:34.179+0000] {processor.py:153} INFO - Started process (PID=696) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:37:34.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:37:34.181+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:37:34.181+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:37:34.186+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:37:34.185+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:37:34.186+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:37:34.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.033 seconds
[2023-04-05T12:38:04.423+0000] {processor.py:153} INFO - Started process (PID=708) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:04.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:38:04.425+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:04.425+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:04.430+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:04.429+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:38:04.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:04.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2023-04-05T12:38:34.619+0000] {processor.py:153} INFO - Started process (PID=720) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:34.620+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:38:34.621+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:34.620+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:34.626+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:34.625+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:38:34.627+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:34.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2023-04-05T12:38:50.730+0000] {processor.py:153} INFO - Started process (PID=732) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:50.731+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:38:50.732+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:50.732+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:50.734+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:50.733+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 2
    from datetime import
                        ^
SyntaxError: invalid syntax
[2023-04-05T12:38:50.734+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:50.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:38:51.749+0000] {processor.py:153} INFO - Started process (PID=737) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:51.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:38:51.750+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:51.750+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:51.756+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:51.755+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 10, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:38:51.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:51.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2023-04-05T12:38:53.797+0000] {processor.py:153} INFO - Started process (PID=742) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:53.798+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:38:53.799+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:53.799+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:53.809+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:38:53.808+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 10, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:38:53.809+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:38:53.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2023-04-05T12:39:24.001+0000] {processor.py:153} INFO - Started process (PID=753) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:24.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:39:24.003+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:39:24.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:24.008+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:39:24.007+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 10, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:39:24.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:24.030+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2023-04-05T12:39:30.076+0000] {processor.py:153} INFO - Started process (PID=758) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:30.077+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:39:30.077+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:39:30.077+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:30.082+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:39:30.081+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:39:30.082+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:30.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:39:33.104+0000] {processor.py:153} INFO - Started process (PID=763) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:33.105+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:39:33.105+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:39:33.105+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:33.111+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:39:33.110+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:39:33.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:39:33.131+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2023-04-05T12:40:03.324+0000] {processor.py:153} INFO - Started process (PID=776) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:40:03.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:40:03.325+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:40:03.325+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:40:03.330+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:40:03.329+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:40:03.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:40:03.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:40:33.538+0000] {processor.py:153} INFO - Started process (PID=788) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:40:33.538+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:40:33.539+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:40:33.539+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:40:33.543+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:40:33.543+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:40:33.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:40:33.561+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:41:03.758+0000] {processor.py:153} INFO - Started process (PID=800) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:41:03.759+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:41:03.759+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:41:03.759+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:41:03.765+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:41:03.764+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:41:03.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:41:03.781+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:41:33.963+0000] {processor.py:153} INFO - Started process (PID=811) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:41:33.963+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:41:33.964+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:41:33.964+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:41:33.968+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:41:33.967+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:41:33.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:41:33.985+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:42:04.125+0000] {processor.py:153} INFO - Started process (PID=824) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:42:04.126+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:42:04.127+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:42:04.127+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:42:04.133+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:42:04.132+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:42:04.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:42:04.149+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:42:34.306+0000] {processor.py:153} INFO - Started process (PID=836) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:42:34.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:42:34.307+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:42:34.307+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:42:34.311+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:42:34.311+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:42:34.311+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:42:34.327+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T12:43:04.566+0000] {processor.py:153} INFO - Started process (PID=848) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:43:04.567+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:43:04.568+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:43:04.568+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:43:04.573+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:43:04.572+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:43:04.573+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:43:04.590+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2023-04-05T12:43:34.751+0000] {processor.py:153} INFO - Started process (PID=860) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:43:34.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:43:34.753+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:43:34.752+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:43:34.758+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:43:34.757+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:43:34.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:43:34.781+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.033 seconds
[2023-04-05T12:44:04.990+0000] {processor.py:153} INFO - Started process (PID=873) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:44:04.990+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:44:04.991+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:44:04.991+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:44:04.996+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:44:04.996+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:44:04.997+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:44:05.017+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2023-04-05T12:44:35.177+0000] {processor.py:153} INFO - Started process (PID=886) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:44:35.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:44:35.178+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:44:35.178+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:44:35.184+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:44:35.183+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:44:35.184+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:44:35.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:45:05.463+0000] {processor.py:153} INFO - Started process (PID=898) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:05.463+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:45:05.464+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:05.464+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:05.469+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:05.468+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 12, in <module>
    'retry_delay': datetime.timedelta(minutes=2),
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[2023-04-05T12:45:05.469+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:05.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:45:16.547+0000] {processor.py:153} INFO - Started process (PID=903) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:16.548+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:45:16.548+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:16.548+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:16.566+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:16.666+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:16.666+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:45:16.710+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:16.710+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:45:16.743+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.199 seconds
[2023-04-05T12:45:17.574+0000] {processor.py:153} INFO - Started process (PID=908) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:17.574+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:45:17.576+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:17.576+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:17.593+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:17.605+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:17.605+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:45:17.645+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:17.645+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:45:17.667+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.097 seconds
[2023-04-05T12:45:47.798+0000] {processor.py:153} INFO - Started process (PID=921) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:47.798+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:45:47.799+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:47.799+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:47.816+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:45:47.844+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:47.843+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:45:47.886+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:45:47.886+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:45:47.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.111 seconds
[2023-04-05T12:46:18.027+0000] {processor.py:153} INFO - Started process (PID=933) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:46:18.027+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:46:18.028+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:46:18.028+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:46:18.045+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:46:18.074+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:46:18.074+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:46:18.120+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:46:18.120+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:46:18.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.119 seconds
[2023-04-05T12:46:48.241+0000] {processor.py:153} INFO - Started process (PID=945) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:46:48.242+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:46:48.243+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:46:48.243+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:46:48.258+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:46:48.283+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:46:48.283+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:46:48.320+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:46:48.320+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:46:48.341+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.103 seconds
[2023-04-05T12:47:18.496+0000] {processor.py:153} INFO - Started process (PID=957) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:47:18.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:47:18.497+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:47:18.497+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:47:18.514+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:47:18.539+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:47:18.539+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:47:18.588+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:47:18.588+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:47:18.615+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.122 seconds
[2023-04-05T12:47:48.717+0000] {processor.py:153} INFO - Started process (PID=969) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:47:48.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:47:48.718+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:47:48.718+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:47:48.734+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:47:48.762+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:47:48.762+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:47:48.806+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:47:48.806+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:47:48.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.118 seconds
[2023-04-05T12:48:18.987+0000] {processor.py:153} INFO - Started process (PID=1095) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:48:18.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:48:18.988+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:48:18.988+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:48:19.009+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:48:19.047+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:48:19.046+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:48:19.103+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:48:19.102+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-09-06T00:00:00+00:00, run_after=2021-09-07T00:00:00+00:00
[2023-04-05T12:48:19.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.145 seconds
[2023-04-05T12:48:49.228+0000] {processor.py:153} INFO - Started process (PID=1284) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:48:49.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:48:49.229+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:48:49.229+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:48:49.248+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:48:49.281+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:48:49.281+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:48:49.328+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:48:49.328+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2021-11-04T00:00:00+00:00, run_after=2021-11-05T00:00:00+00:00
[2023-04-05T12:48:49.361+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.137 seconds
[2023-04-05T12:49:19.569+0000] {processor.py:153} INFO - Started process (PID=1476) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:49:19.574+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:49:19.575+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:49:19.575+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:49:19.632+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:49:19.683+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:49:19.682+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:49:19.734+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:49:19.734+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-01-06T00:00:00+00:00, run_after=2022-01-07T00:00:00+00:00
[2023-04-05T12:49:19.806+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.244 seconds
[2023-04-05T12:49:50.061+0000] {processor.py:153} INFO - Started process (PID=1680) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:49:50.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:49:50.063+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:49:50.063+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:49:50.090+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:49:50.151+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:49:50.151+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:49:50.210+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:49:50.210+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-03-06T00:00:00+00:00, run_after=2022-03-07T00:00:00+00:00
[2023-04-05T12:49:50.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.189 seconds
[2023-04-05T12:50:20.303+0000] {processor.py:153} INFO - Started process (PID=1833) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:50:20.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:50:20.308+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:50:20.308+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:50:20.336+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:50:20.375+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:50:20.375+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:50:20.435+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:50:20.434+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-04-24T00:00:00+00:00, run_after=2022-04-25T00:00:00+00:00
[2023-04-05T12:50:20.469+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.170 seconds
[2023-04-05T12:50:50.690+0000] {processor.py:153} INFO - Started process (PID=2014) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:50:50.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:50:50.692+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:50:50.692+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:50:50.714+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:50:50.763+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:50:50.762+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:50:50.814+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:50:50.814+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-06-17T00:00:00+00:00, run_after=2022-06-18T00:00:00+00:00
[2023-04-05T12:50:50.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.164 seconds
[2023-04-05T12:51:21.016+0000] {processor.py:153} INFO - Started process (PID=2206) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:21.019+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:51:21.020+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:21.019+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:21.059+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:21.099+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:21.098+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:51:21.159+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:21.158+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-08-19T00:00:00+00:00, run_after=2022-08-20T00:00:00+00:00
[2023-04-05T12:51:21.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.210 seconds
[2023-04-05T12:51:51.417+0000] {processor.py:153} INFO - Started process (PID=2426) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:51.419+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:51:51.419+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:51.419+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:51.474+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:51.543+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:51.543+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:51:51.659+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:51.659+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-10-27T00:00:00+00:00, run_after=2022-10-28T00:00:00+00:00
[2023-04-05T12:51:51.747+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.334 seconds
[2023-04-05T12:51:57.875+0000] {processor.py:153} INFO - Started process (PID=2466) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:57.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:51:57.876+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:57.876+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:57.878+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:51:57.877+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 30
    task1
        ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:51:57.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:51:57.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2023-04-05T12:52:01.896+0000] {processor.py:153} INFO - Started process (PID=2472) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:01.897+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:01.898+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:01.898+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:01.900+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:01.899+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 30
    task1
        ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:52:01.901+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:01.920+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2023-04-05T12:52:03.911+0000] {processor.py:153} INFO - Started process (PID=2477) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:03.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:03.912+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:03.911+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:03.913+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:03.912+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 31
    task1
        ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:52:03.914+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:03.935+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2023-04-05T12:52:05.964+0000] {processor.py:153} INFO - Started process (PID=2482) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:05.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:05.965+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:05.965+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:05.967+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:05.966+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29
    }
    ^
SyntaxError: invalid syntax
[2023-04-05T12:52:05.967+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:05.985+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2023-04-05T12:52:09.988+0000] {processor.py:153} INFO - Started process (PID=2487) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:09.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:09.989+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:09.989+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:10.002+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:10.001+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 28, in <module>
    task2 = BashOperator(
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 377, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-04-05T12:52:10.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:10.020+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2023-04-05T12:52:12.052+0000] {processor.py:153} INFO - Started process (PID=2492) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:12.052+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:12.053+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:12.053+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:12.066+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:12.064+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 28, in <module>
    task2 = BashOperator(
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 377, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-04-05T12:52:12.067+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:12.087+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2023-04-05T12:52:14.075+0000] {processor.py:153} INFO - Started process (PID=2497) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:14.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:14.076+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:14.076+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:14.089+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:14.087+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29, in <module>
    task_id='second_task',
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 377, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-04-05T12:52:14.089+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:14.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2023-04-05T12:52:18.141+0000] {processor.py:153} INFO - Started process (PID=2502) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:18.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:18.142+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:18.142+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:18.155+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:18.153+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29, in <module>
    task_id='second_task',
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 377, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-04-05T12:52:18.155+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:18.175+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2023-04-05T12:52:23.198+0000] {processor.py:153} INFO - Started process (PID=2514) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:23.199+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:23.200+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:23.199+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:23.218+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:23.319+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:23.319+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:52:23.361+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:23.361+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-11-06T00:00:00+00:00, run_after=2022-11-07T00:00:00+00:00
[2023-04-05T12:52:23.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.191 seconds
[2023-04-05T12:52:25.270+0000] {processor.py:153} INFO - Started process (PID=2539) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:25.271+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:25.272+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:25.272+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:25.377+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:25.444+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:25.444+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:52:25.765+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:25.765+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-11-13T00:00:00+00:00, run_after=2022-11-14T00:00:00+00:00
[2023-04-05T12:52:25.874+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.609 seconds
[2023-04-05T12:52:31.970+0000] {processor.py:153} INFO - Started process (PID=2611) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:31.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:31.971+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:31.971+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:31.989+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:31.999+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:31.999+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:52:32.043+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:32.042+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-11-20T00:00:00+00:00, run_after=2022-11-21T00:00:00+00:00
[2023-04-05T12:52:32.073+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.107 seconds
[2023-04-05T12:52:39.037+0000] {processor.py:153} INFO - Started process (PID=2688) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:39.038+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:39.041+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:39.041+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:39.068+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:39.093+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:39.092+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:52:39.177+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:39.173+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-12-03T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2023-04-05T12:52:39.223+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.191 seconds
[2023-04-05T12:52:56.307+0000] {processor.py:153} INFO - Started process (PID=2827) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:56.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:56.312+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:56.312+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:56.337+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:56.336+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 33, in <module>
    task1.et
AttributeError: 'BashOperator' object has no attribute 'et'
[2023-04-05T12:52:56.337+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:56.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.081 seconds
[2023-04-05T12:52:59.400+0000] {processor.py:153} INFO - Started process (PID=2837) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:59.401+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:52:59.402+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:59.401+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:59.413+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:52:59.413+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 33, in <module>
    task1.set
AttributeError: 'BashOperator' object has no attribute 'set'
[2023-04-05T12:52:59.414+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:52:59.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2023-04-05T12:53:01.483+0000] {processor.py:153} INFO - Started process (PID=2842) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:01.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:53:01.484+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:01.484+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:01.505+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:01.600+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:01.600+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:53:01.641+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:01.641+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag to 2022-12-26T00:00:00+00:00, run_after=2022-12-27T00:00:00+00:00
[2023-04-05T12:53:01.671+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.192 seconds
[2023-04-05T12:53:19.834+0000] {processor.py:153} INFO - Started process (PID=3025) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:19.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:53:19.839+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:19.838+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:19.862+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:20.081+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:20.080+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:our_first_dag_v2
[2023-04-05T12:53:20.101+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:20.101+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:our_first_dag_v2
[2023-04-05T12:53:20.117+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:20.117+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:our_first_dag_v2
[2023-04-05T12:53:20.118+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:20.117+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:53:20.145+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:20.145+0000] {dag.py:2726} INFO - Creating ORM DAG for our_first_dag_v2
[2023-04-05T12:53:20.175+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:20.175+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:53:20.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.380 seconds
[2023-04-05T12:53:50.409+0000] {processor.py:153} INFO - Started process (PID=3053) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:50.410+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:53:50.411+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:50.411+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:50.431+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:53:50.461+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:50.461+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:53:50.507+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:53:50.506+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:53:50.550+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.146 seconds
[2023-04-05T12:54:20.609+0000] {processor.py:153} INFO - Started process (PID=3085) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:54:20.611+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:54:20.619+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:54:20.612+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:54:20.656+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:54:20.711+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:54:20.711+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:54:20.761+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:54:20.761+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2021-08-06T00:00:00+00:00, run_after=2021-08-07T00:00:00+00:00
[2023-04-05T12:54:20.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.188 seconds
[2023-04-05T12:54:50.896+0000] {processor.py:153} INFO - Started process (PID=3283) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:54:50.898+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:54:50.898+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:54:50.898+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:54:50.916+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:54:50.945+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:54:50.945+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:54:50.987+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:54:50.986+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2021-09-01T00:00:00+00:00, run_after=2021-09-02T00:00:00+00:00
[2023-04-05T12:54:51.009+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.116 seconds
[2023-04-05T12:55:21.193+0000] {processor.py:153} INFO - Started process (PID=3496) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:55:21.194+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:55:21.195+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:55:21.195+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:55:21.228+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:55:21.264+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:55:21.264+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:55:21.365+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:55:21.365+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2021-10-07T00:00:00+00:00, run_after=2021-10-08T00:00:00+00:00
[2023-04-05T12:55:21.475+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.289 seconds
[2023-04-05T12:55:51.788+0000] {processor.py:153} INFO - Started process (PID=3750) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:55:51.789+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:55:51.789+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:55:51.789+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:55:51.811+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:55:51.848+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:55:51.848+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:55:51.903+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:55:51.903+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2021-11-13T00:00:00+00:00, run_after=2021-11-14T00:00:00+00:00
[2023-04-05T12:55:51.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.152 seconds
[2023-04-05T12:56:22.070+0000] {processor.py:153} INFO - Started process (PID=4057) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:56:22.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:56:22.073+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:56:22.073+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:56:22.133+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:56:22.217+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:56:22.217+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:56:22.447+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:56:22.442+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2022-01-06T00:00:00+00:00, run_after=2022-01-07T00:00:00+00:00
[2023-04-05T12:56:22.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.554 seconds
[2023-04-05T12:56:52.945+0000] {processor.py:153} INFO - Started process (PID=4378) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:56:52.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:56:52.946+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:56:52.946+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:56:52.981+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:56:53.040+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:56:53.040+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:56:53.184+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:56:53.183+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2022-02-27T00:00:00+00:00, run_after=2022-02-28T00:00:00+00:00
[2023-04-05T12:56:53.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.289 seconds
[2023-04-05T12:57:23.528+0000] {processor.py:153} INFO - Started process (PID=4709) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:23.530+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:57:23.532+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:23.532+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:23.551+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:23.593+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:23.593+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:57:23.651+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:23.651+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2022-04-20T00:00:00+00:00, run_after=2022-04-21T00:00:00+00:00
[2023-04-05T12:57:23.708+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.184 seconds
[2023-04-05T12:57:52.949+0000] {processor.py:153} INFO - Started process (PID=5004) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:52.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:57:52.955+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:52.954+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:52.958+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:52.957+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 36
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:57:52.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:52.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.061 seconds
[2023-04-05T12:57:53.943+0000] {processor.py:153} INFO - Started process (PID=5017) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:53.943+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:57:53.944+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:53.944+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:53.946+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:57:53.945+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 36
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:57:53.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:57:53.968+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2023-04-05T12:58:02.986+0000] {processor.py:153} INFO - Started process (PID=5022) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:02.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:02.988+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:02.988+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:02.989+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:02.989+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 37
    task1.set_downstream(task2)
        ^
SyntaxError: invalid syntax
[2023-04-05T12:58:02.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:03.007+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T12:58:03.997+0000] {processor.py:153} INFO - Started process (PID=5027) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:03.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:03.998+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:03.998+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:04.000+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:03.999+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 37
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:58:04.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:04.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2023-04-05T12:58:17.102+0000] {processor.py:153} INFO - Started process (PID=5032) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:17.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:17.103+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:17.103+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:17.105+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:17.104+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 37
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:58:17.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:17.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2023-04-05T12:58:26.158+0000] {processor.py:153} INFO - Started process (PID=5045) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:26.158+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:26.159+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:26.159+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:26.161+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:26.160+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 37
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:58:26.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:26.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2023-04-05T12:58:34.230+0000] {processor.py:153} INFO - Started process (PID=5050) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:34.230+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:34.231+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:34.231+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:34.233+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:34.232+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 37
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:58:34.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:34.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2023-04-05T12:58:42.271+0000] {processor.py:153} INFO - Started process (PID=5055) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:42.272+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:42.273+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:42.272+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:42.274+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:42.274+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 38
    task1.set_downstream(task2)
                              ^
SyntaxError: unexpected EOF while parsing
[2023-04-05T12:58:42.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:42.299+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2023-04-05T12:58:43.318+0000] {processor.py:153} INFO - Started process (PID=5060) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:43.319+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:43.320+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:43.320+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:43.337+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:43.451+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:43.451+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:58:43.498+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:43.498+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2022-06-06T00:00:00+00:00, run_after=2022-06-07T00:00:00+00:00
[2023-04-05T12:58:43.534+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.220 seconds
[2023-04-05T12:58:47.403+0000] {processor.py:153} INFO - Started process (PID=5136) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:47.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:47.404+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:47.404+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:47.463+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:47.512+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:47.512+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:58:47.656+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:47.656+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2022-06-15T00:00:00+00:00, run_after=2022-06-16T00:00:00+00:00
[2023-04-05T12:58:47.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.363 seconds
[2023-04-05T12:58:48.655+0000] {processor.py:153} INFO - Started process (PID=5161) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:48.655+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:58:48.656+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:48.656+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:48.681+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:58:48.693+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:48.692+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:58:48.741+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:58:48.740+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v2 to 2022-06-15T00:00:00+00:00, run_after=2022-06-16T00:00:00+00:00
[2023-04-05T12:58:48.769+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.118 seconds
[2023-04-05T12:59:04.727+0000] {processor.py:153} INFO - Started process (PID=5252) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:04.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:59:04.728+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.728+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:04.750+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:04.923+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.922+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:our_first_dag_v3
[2023-04-05T12:59:04.939+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.939+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:our_first_dag_v3
[2023-04-05T12:59:04.948+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.948+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:our_first_dag_v3
[2023-04-05T12:59:04.948+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.948+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:59:04.971+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.971+0000] {dag.py:2726} INFO - Creating ORM DAG for our_first_dag_v3
[2023-04-05T12:59:04.990+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:04.990+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:59:05.012+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.289 seconds
[2023-04-05T12:59:06.041+0000] {processor.py:153} INFO - Started process (PID=5257) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:06.042+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:59:06.043+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:06.043+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:06.063+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:06.077+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:06.077+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:59:06.130+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:06.130+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:59:06.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.124 seconds
[2023-04-05T12:59:36.210+0000] {processor.py:153} INFO - Started process (PID=5270) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:36.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T12:59:36.211+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:36.211+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:36.233+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T12:59:36.265+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:36.264+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T12:59:36.313+0000] {logging_mixin.py:137} INFO - [2023-04-05T12:59:36.313+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T12:59:36.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.136 seconds
[2023-04-05T13:00:06.489+0000] {processor.py:153} INFO - Started process (PID=5288) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:00:06.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:00:06.491+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:00:06.490+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:00:06.510+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:00:06.543+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:00:06.543+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:00:06.592+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:00:06.592+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:00:06.626+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.141 seconds
[2023-04-05T13:00:36.658+0000] {processor.py:153} INFO - Started process (PID=5300) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:00:36.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:00:36.660+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:00:36.660+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:00:36.688+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:00:36.730+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:00:36.729+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:00:36.783+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:00:36.783+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:00:36.812+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.158 seconds
[2023-04-05T13:01:06.979+0000] {processor.py:153} INFO - Started process (PID=5312) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:01:06.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:01:06.981+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:01:06.981+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:01:07.002+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:01:07.033+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:01:07.033+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:01:07.085+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:01:07.085+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:01:07.121+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.145 seconds
[2023-04-05T13:01:37.345+0000] {processor.py:153} INFO - Started process (PID=5554) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:01:37.345+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:01:37.353+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:01:37.353+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:01:37.429+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:01:37.607+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:01:37.607+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:01:37.909+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:01:37.906+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-08-28T00:00:00+00:00, run_after=2021-08-29T00:00:00+00:00
[2023-04-05T13:01:38.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.690 seconds
[2023-04-05T13:02:08.430+0000] {processor.py:153} INFO - Started process (PID=5883) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:02:08.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:02:08.439+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:02:08.439+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:02:08.482+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:02:08.622+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:02:08.622+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:02:08.828+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:02:08.828+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-10-04T00:00:00+00:00, run_after=2021-10-05T00:00:00+00:00
[2023-04-05T13:02:09.015+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.590 seconds
[2023-04-05T13:02:39.142+0000] {processor.py:153} INFO - Started process (PID=6222) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:02:39.143+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:02:39.144+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:02:39.144+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:02:39.187+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:02:39.222+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:02:39.221+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:02:39.306+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:02:39.305+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-11-08T00:00:00+00:00, run_after=2021-11-09T00:00:00+00:00
[2023-04-05T13:02:39.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.242 seconds
[2023-04-05T13:03:09.475+0000] {processor.py:153} INFO - Started process (PID=6580) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:09.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:03:09.479+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:09.479+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:09.507+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:09.557+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:09.556+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:03:09.616+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:09.615+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2021-12-12T00:00:00+00:00, run_after=2021-12-13T00:00:00+00:00
[2023-04-05T13:03:09.657+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.187 seconds
[2023-04-05T13:03:36.009+0000] {processor.py:153} INFO - Started process (PID=6851) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:36.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:03:36.011+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:36.011+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:36.081+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:36.361+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:36.343+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:03:36.606+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:36.606+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2022-01-16T00:00:00+00:00, run_after=2022-01-17T00:00:00+00:00
[2023-04-05T13:03:36.801+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.795 seconds
[2023-04-05T13:03:40.807+0000] {processor.py:153} INFO - Started process (PID=6925) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:40.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:03:40.808+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:40.808+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:40.810+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:40.810+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 41
    task1 >>
           ^
SyntaxError: invalid syntax
[2023-04-05T13:03:40.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:40.828+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2023-04-05T13:03:42.822+0000] {processor.py:153} INFO - Started process (PID=6930) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:42.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:03:42.824+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:42.824+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:42.848+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:42.859+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:42.858+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:03:42.905+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:42.905+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v3 to 2022-01-17T00:00:00+00:00, run_after=2022-01-18T00:00:00+00:00
[2023-04-05T13:03:42.935+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.116 seconds
[2023-04-05T13:03:50.917+0000] {processor.py:153} INFO - Started process (PID=7015) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:50.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:03:50.918+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:50.918+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:50.936+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:50.945+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:50.945+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:03:51.008+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.094 seconds
[2023-04-05T13:03:57.965+0000] {processor.py:153} INFO - Started process (PID=7027) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:57.965+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:03:57.966+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:57.966+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:57.982+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v3']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:03:57.995+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:03:57.995+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:03:58.061+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.099 seconds
[2023-04-05T13:04:04.092+0000] {processor.py:153} INFO - Started process (PID=7032) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:04:04.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:04:04.093+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.093+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:04:04.113+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:04:04.264+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.264+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:our_first_dag_v4
[2023-04-05T13:04:04.276+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.275+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:our_first_dag_v4
[2023-04-05T13:04:04.282+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.282+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:our_first_dag_v4
[2023-04-05T13:04:04.282+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.282+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:04:04.305+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.305+0000] {dag.py:2726} INFO - Creating ORM DAG for our_first_dag_v4
[2023-04-05T13:04:04.323+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:04.323+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:04:04.341+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.252 seconds
[2023-04-05T13:04:34.499+0000] {processor.py:153} INFO - Started process (PID=7044) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:04:34.500+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:04:34.501+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:34.500+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:04:34.517+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:04:34.544+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:34.544+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:04:34.582+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:04:34.582+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:04:34.604+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.109 seconds
[2023-04-05T13:05:04.655+0000] {processor.py:153} INFO - Started process (PID=7056) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:04.656+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:05:04.657+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:04.657+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:04.677+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:04.708+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:04.708+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:05:04.752+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:04.752+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:05:04.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.128 seconds
[2023-04-05T13:05:34.956+0000] {processor.py:153} INFO - Started process (PID=7068) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:34.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:05:34.957+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:34.957+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:34.977+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:35.006+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:35.006+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:05:35.048+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:35.048+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:05:35.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.116 seconds
[2023-04-05T13:05:49.056+0000] {processor.py:153} INFO - Started process (PID=7073) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:49.057+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:05:49.057+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:49.057+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:49.078+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:49.181+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:49.181+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:05:49.225+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:49.225+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:05:49.254+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.201 seconds
[2023-04-05T13:05:50.160+0000] {processor.py:153} INFO - Started process (PID=7078) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:50.161+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:05:50.162+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:50.162+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:50.181+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:50.193+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:50.192+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:05:50.236+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:50.236+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:05:50.257+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.100 seconds
[2023-04-05T13:05:52.179+0000] {processor.py:153} INFO - Started process (PID=7083) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:52.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:05:52.180+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:52.180+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:52.202+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:52.214+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:52.214+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:05:52.253+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:52.253+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:05:52.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.101 seconds
[2023-04-05T13:05:58.316+0000] {processor.py:153} INFO - Started process (PID=7095) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:58.316+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:05:58.317+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:58.317+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:58.334+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:05:58.343+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:58.343+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:05:58.381+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:05:58.381+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:05:58.400+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.087 seconds
[2023-04-05T13:06:02.352+0000] {processor.py:153} INFO - Started process (PID=7100) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:02.353+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:06:02.354+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:02.354+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:02.376+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:02.388+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:02.388+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:06:02.431+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:02.430+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:06:02.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.102 seconds
[2023-04-05T13:06:06.468+0000] {processor.py:153} INFO - Started process (PID=7105) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:06.469+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:06:06.469+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:06.469+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:06.485+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:06.496+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:06.496+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:06:06.533+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:06.533+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:06:06.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.086 seconds
[2023-04-05T13:06:08.510+0000] {processor.py:153} INFO - Started process (PID=7110) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:08.510+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:06:08.511+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:08.511+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:08.534+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:08.549+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:08.549+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:06:08.599+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:08.599+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:06:08.626+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.121 seconds
[2023-04-05T13:06:19.644+0000] {processor.py:153} INFO - Started process (PID=7115) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:19.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:06:19.645+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:19.645+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:19.662+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:19.687+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:19.687+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:06:19.725+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:19.725+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:06:19.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.112 seconds
[2023-04-05T13:06:49.850+0000] {processor.py:153} INFO - Started process (PID=7127) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:49.851+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:06:49.851+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:49.851+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:49.869+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:49.894+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:49.893+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:06:49.938+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:49.938+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:06:49.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.113 seconds
[2023-04-05T13:06:50.859+0000] {processor.py:153} INFO - Started process (PID=7132) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:50.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:06:50.860+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:50.860+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:50.880+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:06:50.981+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:50.981+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:06:51.021+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:06:51.021+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:06:51.044+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.188 seconds
[2023-04-05T13:07:21.194+0000] {processor.py:153} INFO - Started process (PID=7145) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:21.195+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:07:21.196+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:21.196+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:21.214+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v4']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:21.243+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:21.243+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:07:21.288+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:21.288+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v4 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:07:21.309+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.118 seconds
[2023-04-05T13:07:43.473+0000] {processor.py:153} INFO - Started process (PID=7157) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:43.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:07:43.475+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.475+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:43.497+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:43.666+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.666+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:our_first_dag_v5
[2023-04-05T13:07:43.681+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.681+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:our_first_dag_v5
[2023-04-05T13:07:43.691+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.691+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:our_first_dag_v5
[2023-04-05T13:07:43.691+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.691+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:07:43.715+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.714+0000] {dag.py:2726} INFO - Creating ORM DAG for our_first_dag_v5
[2023-04-05T13:07:43.735+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:43.734+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:07:43.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.288 seconds
[2023-04-05T13:07:44.486+0000] {processor.py:153} INFO - Started process (PID=7162) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:44.487+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:07:44.488+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:44.487+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:44.508+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:07:44.525+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:44.524+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:07:44.579+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:07:44.578+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2023-04-05T13:07:44.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.123 seconds
[2023-04-05T13:08:14.660+0000] {processor.py:153} INFO - Started process (PID=7177) to work on /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:08:14.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-04-05T13:08:14.662+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:08:14.662+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:08:14.696+0000] {processor.py:753} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2023-04-05T13:08:14.757+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:08:14.756+0000] {dag.py:2705} INFO - Sync 1 DAGs
[2023-04-05T13:08:14.836+0000] {logging_mixin.py:137} INFO - [2023-04-05T13:08:14.835+0000] {dag.py:3456} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-08-03T00:00:00+00:00, run_after=2021-08-04T00:00:00+00:00
[2023-04-05T13:08:14.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.243 seconds
