[2023-04-07T13:24:38.922+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_posgres_operator_v01.create_postgres_table scheduled__2023-04-05T00:00:00+00:00 [queued]>
[2023-04-07T13:24:38.938+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_posgres_operator_v01.create_postgres_table scheduled__2023-04-05T00:00:00+00:00 [queued]>
[2023-04-07T13:24:38.939+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T13:24:38.939+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-07T13:24:38.939+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T13:24:38.964+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-04-05 00:00:00+00:00
[2023-04-07T13:24:38.969+0000] {standard_task_runner.py:55} INFO - Started process 1089 to run task
[2023-04-07T13:24:38.971+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_posgres_operator_v01', 'create_postgres_table', 'scheduled__2023-04-05T00:00:00+00:00', '--job-id', '6785', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp59d7of0u']
[2023-04-07T13:24:38.972+0000] {standard_task_runner.py:83} INFO - Job 6785: Subtask create_postgres_table
[2023-04-07T13:24:39.039+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_posgres_operator_v01.create_postgres_table scheduled__2023-04-05T00:00:00+00:00 [running]> on host ce9c8327347b
[2023-04-07T13:24:39.161+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=dag_with_posgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-05T00:00:00+00:00
[2023-04-07T13:24:39.162+0000] {sql.py:254} INFO - Executing: 
            create table if not exist_dag_runs (
                dt date,
                dag_id charater varying,
                primary key (dt, dag_id)
            )
        
[2023-04-07T13:24:39.193+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-04-07T13:24:39.200+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_posgres_operator_v01, task_id=create_postgres_table, execution_date=20230405T000000, start_date=20230407T132438, end_date=20230407T132439
[2023-04-07T13:24:39.216+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6785 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 1089)
[2023-04-07T13:24:39.231+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-07T13:24:39.255+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
