[2023-04-07T13:41:05.484+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_posgres_operator_v02.insert_into_table manual__2023-04-07T13:41:03.252235+00:00 [queued]>
[2023-04-07T13:41:05.496+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_posgres_operator_v02.insert_into_table manual__2023-04-07T13:41:03.252235+00:00 [queued]>
[2023-04-07T13:41:05.496+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T13:41:05.497+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-07T13:41:05.497+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T13:41:05.521+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-04-07 13:41:03.252235+00:00
[2023-04-07T13:41:05.524+0000] {standard_task_runner.py:55} INFO - Started process 1701 to run task
[2023-04-07T13:41:05.526+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_posgres_operator_v02', 'insert_into_table', 'manual__2023-04-07T13:41:03.252235+00:00', '--job-id', '6828', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp09_jbk53']
[2023-04-07T13:41:05.527+0000] {standard_task_runner.py:83} INFO - Job 6828: Subtask insert_into_table
[2023-04-07T13:41:05.588+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_posgres_operator_v02.insert_into_table manual__2023-04-07T13:41:03.252235+00:00 [running]> on host ce9c8327347b
[2023-04-07T13:41:05.683+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=dag_with_posgres_operator_v02
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-07T13:41:03.252235+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-07T13:41:03.252235+00:00
[2023-04-07T13:41:05.683+0000] {sql.py:254} INFO - Executing: 
            insert into dag_runs (ds, dag_id) values ('2023-04-07', 'dag_with_posgres_operator_v02')
        
[2023-04-07T13:41:05.691+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-04-07T13:41:06.024+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-04-07T13:41:06.026+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs (ds, dag_id) values ('2023-04-07', 'dag_with_posgres_operator_v02')
        , parameters: None
[2023-04-07T13:41:06.026+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "ds" of relation "dag_runs" does not exist
LINE 2:             insert into dag_runs (ds, dag_id) values ('2023-...
                                          ^

[2023-04-07T13:41:06.033+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_posgres_operator_v02, task_id=insert_into_table, execution_date=20230407T134103, start_date=20230407T134105, end_date=20230407T134106
[2023-04-07T13:41:06.044+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6828 for task insert_into_table (column "ds" of relation "dag_runs" does not exist
LINE 2:             insert into dag_runs (ds, dag_id) values ('2023-...
                                          ^
; 1701)
[2023-04-07T13:41:06.068+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-07T13:41:06.086+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
