[2023-04-06T13:32:06.325+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2023-04-06T13:32:06.355+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_dag_with_python_operator_v06.get_name scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2023-04-06T13:32:06.356+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:32:06.356+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-06T13:32:06.357+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T13:32:06.469+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_name> on 2022-05-28 00:00:00+00:00
[2023-04-06T13:32:06.490+0000] {standard_task_runner.py:55} INFO - Started process 4689 to run task
[2023-04-06T13:32:06.503+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_dag_with_python_operator_v06', 'get_name', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '4647', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpcu23uxic']
[2023-04-06T13:32:06.504+0000] {standard_task_runner.py:83} INFO - Job 4647: Subtask get_name
[2023-04-06T13:32:06.567+0000] {local_task_job.py:113} ERROR - Received SIGTERM. Terminating subprocesses
[2023-04-06T13:32:06.592+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4689. PIDs of all processes in the group: [4689]
[2023-04-06T13:32:06.592+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4689
[2023-04-06T13:32:06.609+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4689, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='13:32:05') (4689) terminated with exit code Negsignal.SIGTERM
[2023-04-06T13:32:06.610+0000] {local_task_job.py:212} INFO - Task exited with return code 143
[2023-04-06T13:32:06.769+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
